export const states = new Map([
    ['Alabama', { supervised: 15, license: 16, dropout: 17, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Alaska', { supervised: 14, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Arizona', { supervised: 16, license: 16, dropout: 18, marriage: 18, consent: 18, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Arkansas', { supervised: 14, license: 18, dropout: 17, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['California', { supervised: 15, license: 18, dropout: 18, marriage: 18, consent: 18, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Colorado', { supervised: 15, license: 17, dropout: 17, marriage: 18, consent: 17, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Connecticut', { supervised: 16, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Delaware', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 18, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['District of Columbia', { supervised: 15, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Florida', { supervised: 15, license: 18, dropout: 16, marriage: 18, consent: 18, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 16 }],
    ['Georgia', { supervised: 15, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 17, drinkingAlcohol: 21, tattoo: 18 }],
    ['Hawaii', { supervised: 15, license: 17, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Idaho', { supervised: 14, license: 16, dropout: 16, marriage: 18, consent: 18, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 14 }],
    ['Illinois', { supervised: 15, license: 18, dropout: 17, marriage: 18, consent: 17, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Indiana', { supervised: 15, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Iowa', { supervised: 14, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Kansas', { supervised: 14, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Kentucky', { supervised: 16, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Louisiana', { supervised: 15, license: 17, dropout: 18, marriage: 18, consent: 17, gambling: 21, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Maine', { supervised: 15, license: 16, dropout: 17, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Maryland', { supervised: 15, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Massachusetts', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Michigan', { supervised: 14, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 17, drinkingAlcohol: 21, tattoo: 18 }],
    ['Minnesota', { supervised: 15, license: 17, dropout: 17, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Mississippi', { supervised: 15, license: 16, dropout: 17, marriage: 21, consent: 16, gambling: 21, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Missouri', { supervised: 15, license: 18, dropout: 17, marriage: 18, consent: 17, gambling: 18, adultCharge: 17, drinkingAlcohol: 21, tattoo: 18 }],
    ['Montana', { supervised: 14, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Nebraska', { supervised: 15, license: 18, dropout: 18, marriage: 19, consent: 17, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Nevada', { supervised: 15, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 21, adultCharge: 21, drinkingAlcohol: 21, tattoo: 18 }],
    ['New Hampshire', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['New Jersey', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 16 }],
    ['New Mexico', { supervised: 15, license: 18, dropout: 17, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['New York', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 16, drinkingAlcohol: 21, tattoo: 18 }],
    ['North Carolina', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 16, drinkingAlcohol: 21, tattoo: 18 }],
    ['North Dakota', { supervised: 14, license: 21, dropout: 18, marriage: 18, consent: 16, gambling: 21, adultCharge: 21, drinkingAlcohol: 21, tattoo: 18 }],
    ['Ohio', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Oklahoma', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Oregon', { supervised: 15, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Pennsylvania', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Puerto Rico', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Rhode Island', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['South Carolina', { supervised: 16, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 21, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['South Dakota', { supervised: 14, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 21, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Tennessee', { supervised: 15, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Texas', { supervised: 15, license: 17, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 17, drinkingAlcohol: 21, tattoo: 18 }],
    ['Utah', { supervised: 15, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Vermont', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Virgin Islands', { supervised: 15, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Virginia', { supervised: 15, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Washington', { supervised: 15, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['West Virginia', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Wisconsin', { supervised: 15, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 17, drinkingAlcohol: 21, tattoo: 18 }],
    ['Wyoming', { supervised: 15, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 21, tattoo: 18 }],
    ['Yukon', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
    ['Northwest Territories', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
    ['Nunavut', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
    ['British Columbia', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
    ['Alberta', { supervised: 14, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 18, tattoo: 18 }],
    ['Saskatchewan', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
    ['Manitoba', { supervised: 15, license: 16, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 18, tattoo: 18 }],
    ['Ontario', { supervised: 16, license: 18, dropout: 18, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
    ['Quebec', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 18, adultCharge: 18, drinkingAlcohol: 18, tattoo: 18 }],
    ['New Brunswick', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
    ['Nova Scotia', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
    ['Prince Edward Island', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
    ['Newfoundland and Labrador', { supervised: 16, license: 18, dropout: 16, marriage: 18, consent: 16, gambling: 19, adultCharge: 18, drinkingAlcohol: 19, tattoo: 18 }],
  ]);
  
  export const stateAbbreviations = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA',
    'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'District of Columbia': 'DC',
    'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL',
    'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA',
    'Maine': 'ME', 'Maryland': 'MD', 'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN',
    'Mississippi': 'MS', 'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV',
    'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY',
    'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK', 'Oregon': 'OR',
    'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD',
    'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA',
    'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY',
    'Yukon': 'YT', 'Northwest Territories': 'NT', 'Nunavut': 'NU', 'British Columbia': 'BC', 'Alberta': 'AB',
    'Saskatchewan': 'SK', 'Manitoba': 'MB', 'Ontario': 'ON', 'Quebec': 'QC', 'New Brunswick': 'NB',
    'Nova Scotia': 'NS', 'Prince Edward Island': 'PE', 'Newfoundland and Labrador': 'NL',
  };

   export const stateAbbrArray = [
      ['YT', 'NT', 'NU'],
      ['BC', 'AB', 'SK', 'MB', 'ON', 'QC', 'NB', 'NS', 'PE', 'NL'],
      ['WA', 'OR', 'ID', 'MT', 'ND', 'MN', 'WI', 'MI', 'NY', 'VT', 'NH', 'ME'],
      ['CA', 'NV', 'UT', 'WY', 'SD', 'IA', 'IL', 'IN', 'OH', 'PA', 'NJ', 'CT', 'RI', 'MA'],
      ['AK', 'HI', 'AZ', 'CO', 'NE', 'MO', 'KY', 'WV', 'VA', 'MD', 'DE'],
      ['NM', 'KS', 'AR', 'TN', 'NC', 'SC'],
      ['TX', 'OK', 'LA', 'MS', 'AL', 'GA'],
      ['FL']
    ];
  
  
  